"""add is_legacy to DBTask

Revision ID: 2d65db9b8e2d
Revises: c3f8a12d9b47
Create Date: 2026-06-07 12:07:34.055616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d65db9b8e2d'
down_revision: Union[str, Sequence[str], None] = 'c3f8a12d9b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('is_legacy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'is_legacy')
    # ### end Alembic commands ###
