"""create thesis reviews table

Revision ID: 37a8252523dd
Revises: b34578df9aaa
Create Date: 2026-09-28 10:47:03.556004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a8252523dd'
down_revision: Union[str, Sequence[str], None] = 'b34578df9aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('finished_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_reviews_id'), 'thesis_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_thesis_reviews_thesis_id'), 'thesis_reviews', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_reviews_thesis_id'), table_name='thesis_reviews')
    op.drop_index(op.f('ix_thesis_reviews_id'), table_name='thesis_reviews')
    op.drop_table('thesis_reviews')
    # ### end Alembic commands ###
