"""add is_favorite to assets

Revision ID: a9dd56fd61c5
Revises: 2a6e75764e6b
Create Date: 2026-03-19 16:14:04.444168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9dd56fd61c5'
down_revision: Union[str, Sequence[str], None] = '2a6e75764e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'is_favorite')
    # ### end Alembic commands ###
