"""create thesis news table

Revision ID: b34578df9aaa
Revises: d573f96502ba
Create Date: 2026-09-28 09:52:45.009894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34578df9aaa'
down_revision: Union[str, Sequence[str], None] = 'd573f96502ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('found_at', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('step', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('materiality', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('seen', sa.Boolean(), nullable=True),
    sa.Column('in_timeline', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_news_id'), 'thesis_news', ['id'], unique=False)
    op.create_index(op.f('ix_thesis_news_thesis_id'), 'thesis_news', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_news_thesis_id'), table_name='thesis_news')
    op.drop_index(op.f('ix_thesis_news_id'), table_name='thesis_news')
    op.drop_table('thesis_news')
    # ### end Alembic commands ###
