"""create thesis tracking tables

Revision ID: d573f96502ba
Revises: ed74ef745a69
Create Date: 2026-09-28 08:27:02.885253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd573f96502ba'
down_revision: Union[str, Sequence[str], None] = 'ed74ef745a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('reference_date', sa.String(), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theses_id'), 'theses', ['id'], unique=False)
    op.create_index(op.f('ix_theses_ticker'), 'theses', ['ticker'], unique=True)
    op.create_table('thesis_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('impact', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_events_id'), 'thesis_events', ['id'], unique=False)
    op.create_index(op.f('ix_thesis_events_thesis_id'), 'thesis_events', ['thesis_id'], unique=False)
    op.create_table('thesis_pillars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_pillars_id'), 'thesis_pillars', ['id'], unique=False)
    op.create_table('thesis_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('pillar_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('how_to_measure', sa.String(), nullable=True),
    sa.Column('baseline', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('green_threshold', sa.Float(), nullable=True),
    sa.Column('red_threshold', sa.Float(), nullable=True),
    sa.Column('green_text', sa.String(), nullable=True),
    sa.Column('amber_text', sa.String(), nullable=True),
    sa.Column('red_text', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('auto_metric', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_kill_switch', sa.Boolean(), nullable=True),
    sa.Column('kill_rule', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pillar_id'], ['thesis_pillars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_kpis_id'), 'thesis_kpis', ['id'], unique=False)
    op.create_table('kpi_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kpi_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_id'], ['thesis_kpis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_observations_id'), 'kpi_observations', ['id'], unique=False)
    op.create_index(op.f('ix_kpi_observations_kpi_id'), 'kpi_observations', ['kpi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_observations_kpi_id'), table_name='kpi_observations')
    op.drop_index(op.f('ix_kpi_observations_id'), table_name='kpi_observations')
    op.drop_table('kpi_observations')
    op.drop_index(op.f('ix_thesis_kpis_id'), table_name='thesis_kpis')
    op.drop_table('thesis_kpis')
    op.drop_index(op.f('ix_thesis_pillars_id'), table_name='thesis_pillars')
    op.drop_table('thesis_pillars')
    op.drop_index(op.f('ix_thesis_events_thesis_id'), table_name='thesis_events')
    op.drop_index(op.f('ix_thesis_events_id'), table_name='thesis_events')
    op.drop_table('thesis_events')
    op.drop_index(op.f('ix_theses_ticker'), table_name='theses')
    op.drop_index(op.f('ix_theses_id'), table_name='theses')
    op.drop_table('theses')
    # ### end Alembic commands ###
