"""create thesis decisions table

Revision ID: d5f100a0ff6a
Revises: 37a8252523dd
Create Date: 2026-09-28 11:53:56.612694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f100a0ff6a'
down_revision: Union[str, Sequence[str], None] = '37a8252523dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('health_score', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('transaction_ref', sa.String(), nullable=True),
    sa.Column('lesson', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['thesis_id'], ['theses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thesis_decisions_id'), 'thesis_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_thesis_decisions_thesis_id'), 'thesis_decisions', ['thesis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thesis_decisions_thesis_id'), table_name='thesis_decisions')
    op.drop_index(op.f('ix_thesis_decisions_id'), table_name='thesis_decisions')
    op.drop_table('thesis_decisions')
    # ### end Alembic commands ###
