"""create company lists tables

Revision ID: ed74ef745a69
Revises: 2d65db9b8e2d
Create Date: 2026-07-08 20:51:28.351200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed74ef745a69'
down_revision: Union[str, Sequence[str], None] = '2d65db9b8e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_lists_id'), 'company_lists', ['id'], unique=False)
    op.create_index(op.f('ix_company_lists_name'), 'company_lists', ['name'], unique=True)
    op.create_table('company_list_associations',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['company_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('list_id', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_list_associations')
    op.drop_index(op.f('ix_company_lists_name'), table_name='company_lists')
    op.drop_index(op.f('ix_company_lists_id'), table_name='company_lists')
    op.drop_table('company_lists')
    # ### end Alembic commands ###
